### ISSUE TITLE
Does this library support OAuth2 authentication scope?

### ISSUE THREAD

**Issue by ton212** [samtgarson/nuxt-oauth#12]
I did not see anywhere in the README mentioned authentication scope. How do I define scope with authenticating users with my OAuth server?

**Comment by samtgarson** [comment]
This library currently doesn't support `scope` but I don't think it would be very difficult to add! Should just be a case of adding an attribute to the config (maybe a function which receives the `user` as an argument and returns the desired scope) and then passing that through to the underlying OAuth library...

I don't have a huge amount of time right now but I'll happily accept PRs, otherwise I'll look into this when I get some time.

**Comment by Lahori-Jawan** [comment]
I had to go to `\node_modules\nuxt-oauth\lib\handler.js` to add scope but the side effect is that it reverts back!
